### ISSUE TITLE
v0.15.0-b4 does not build for esp32c3dev target

### ISSUE THREAD

**Issue by berkut0** [wled/WLED#4101]
### What happened?

```
.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:83,
                 from .pio/libdeps/esp32c3dev/FastLED/src/platforms/esp/32/led_sysdefs_esp32.h:2,
                 from .pio/libdeps/esp32c3dev/FastLED/src/led_sysdefs.h:42,
                 from .pio/libdeps/esp32c3dev/FastLED/src/FastLED.h:51,
                 from .pio/libdeps/esp32c3dev/FastLED/src/colorutils.cpp:1
```

```
.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.h:29:10: fatal error: pins_arduino.h: No such file or directory
```

### To Reproduce Bug

Just try building the firmware for esp32c3dev.

### Expected Behavior

The firmware will build for esp32c3dev just as well as it does for version 0.14.4

### Install Method

Self-Compiled

### What version of WLED?

v0.15.0-b4

### Which microcontroller/board are you seeing the problem on?

ESP32-C3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
It does build. Tested every day.
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
