### ISSUE TITLE
Athom LB01 RGB+CW 15W Crashing when turned on.

### ISSUE THREAD

**Issue by bb12ett** [wled/WLED#4127]
### What happened?

The light becomes unresponsive when turned on. This sometimes happens on first use but definitely within the first 5 times it is turned on. The web interface becomes unresponsive, Home Assistant Device becomes unavailable.  

### To Reproduce Bug

When turning on the light from web interface or Home Assistant. Power off and Back on fixes for a couple of uses but becomes unresponsive again. This has happened since I have updated to 14.4 (from 13.3) i have since tried  14.1, 14.2, 14.3 and 15.0-b4 but the issue is present on all firmwares newer than 13.3.

### Expected Behavior

Turn On/Off when required

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.15.0-b4 (build 2406290)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Make sure CCT blending is at 0 and you are using CCT IC enabled version.
And please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions. Athom 15W bulbs are special and need proper binary and setup.
